### ISSUE TITLE
USER STORY: World map

### ISSUE THREAD

**Issue by SandraBergstrom** [SandraBergstrom/team-8#2]
As a user, I want to **view a world map on the homepage**, so that I can easily navigate to different countries and/or cities for their countdowns.

Acceptance Criteria 
- [x] World map is visible on the homepage. 
- [x] Users can interact with the map to select a country or city.
- [x] Upon selection, the website displays a countdown to New Year specific to that location.
- [x] The website also provides some additional information about the selected location.

Tasks
- [x] Evaluate and integrate map.box or a similar mapping service into the website.
- [x] Design and implement a user interface for selecting countries and cities on the map.
- [x] Develop the functionality to calculate and display the countdown based on the selected location's timezone.
- [x] Research and implement a feature to provide additional information about each location (e.g., cultural facts, local New Year traditions).

**Comment by DarrachBarneveld** [comment]
We need to have a group discussion on this. I was able to geolocate based on map position and render some location specific information but involves a backend to fetch API info from Googles APIs, no work around I can think of atm.
