### ISSUE TITLE
USER STORY:  Country Information

### ISSUE THREAD

**Issue by SandraBergstrom** [SandraBergstrom/team-8#5]
As a user, I want to **access brief information about each country I select, such as cultural New Year traditions or interesting facts**, to learn more about how New Year's is celebrated there.

Acceptance Criteria:
- [x] Users can click on or interact with a selected country on the website to access additional information.
- [x] When a country is selected, a popup/information panel/new page appears with relevant details about New Year's traditions or interesting facts about that country's celebrations.

Tasks
- [x] Create a design for the information panel or popup that will display country-specific information.
- [x] Ensure it fits seamlessly into the website's overall design.
- [x] Research and gather concise and interesting information about New Year's traditions or facts for various countries.
- [x] Develop the code to dynamically load and display the relevant content in the information panel based on the selected country.
- [x] Test the user interaction for selecting a country and viewing the information panel on different devices and  to ensure it works smoothly.

**Comment by Dayana-N** [comment]
complete
