### ISSUE TITLE
USER STORY:  Navigation

### ISSUE THREAD

**Issue by SandraBergstrom** [SandraBergstrom/team-8#6]
As a User, I can navigate between different sections of the website so that I can easily access the information or features I need.

Acceptance Cirteria
- [x] The website's navigation menu is prominently displayed and easily accessible from any page if more than one.
- [x] Clicking on a navigation menu item takes the user to the corresponding section or page.
- [x] There is a "Home" link in the navigation menu that allows users to return to the homepage.
- [x] The navigation is responsive and works well on both desktop and mobile devices.

Tasks
- [x] Create a design for the navigation menu that includes clear labels and ensures it fits well with the website's overall design.
- [x] Develop the code for the navigation menu.
- [x] Test the navigation menu to ensure that clicking on each menu item takes the user to the correct destination.
- [x] Implement responsive design techniques to ensure the navigation menu functions effectively on mobile devices.

**Comment by Dayana-N** [comment]
completed
