### ISSUE TITLE
USER Story: Main structure

### ISSUE THREAD

**Issue by bartoszgebarowski** [SandraBergstrom/team-8#8]
As a developer, I need to create a proper structure so everyone in the team can work independently without accessing the main branch.

Acceptance criteria 
- [x] file structure that is  easy to understand
- [x] folder structure that allows team members to work independently of each other work

**Comment by SandraBergstrom** [comment]
@bartoszgebarowski can I put this as done?

**Comment by bartoszgebarowski** [comment]
Sure, I will just add another task to fix the paths for relative paths if that will be needed
