### ISSUE TITLE
USER STORY: Documentation

### ISSUE THREAD

**Issue by SandraBergstrom** [SandraBergstrom/team-8#9]
As a User and a Developer, I want to have a well-documented README file for this project so that I can easily understand its purpose, how to set it up, and how to use it effectively.

Acceptance Criteria:
- [x] The project's README file should be well-structured and organized for easy readability.

Task:
- [x] Create a new README file or update the existing one in the project repository.
- [x] Write a clear and concise project description that explains its purpose and goals.
- [x] Provide clear instructions and examples on how to use the project's features effectively.
- [x] Add a table of contents and section headers to improve readability and navigation within the README.

**Comment by 57Esther** [comment]
To be completed.
